#!/usr/bin/with-contenv bash

# cleanup pid if it exists
[[ -e /config/rtdclient.pid ]] && \
	rm -rf /config/rtdclient.pid

[[ -e /data/rtdclient.pid ]] && \
	rm -rf /data/rtdclient.pid

# permissions
echo "Setting permissions"
chown -R abc:abc \
	/app /data
